#!/usr/bin/env bash

zscroll -l 30 --delay 0.30 \
    --scroll-padding " 󰎆  " \
    --match-command "playerctl status" \
    --match-text "Playing" "--before-text '󰐊 ' --scroll 1" \
    --match-text "Paused" "--before-text '󰏤 ' --scroll 0" \
    --update-check true \
    --update-interval 0.2 \
    'playerctl metadata --format "{{ title }} - {{ artist }}"'
