local home = os.getenv("HOME")
package.path = package.path .. ";" .. home .. "/.config/hypr/?.lua;"

local function load_my_config()
	hl.config({ autogenerated = false })
	local state = require("lua.active_state")

	require("lua.core.settings")
	require("lua.core.keybinds")
	require("lua.core.autostart")
	require("lua.core.rules")
	require("lua.profiles.monitors." .. state.monitor_profile)
end

local success, error_message = pcall(load_my_config)
if not success then
	local log_file = io.open(home .. "/.config/hypr/lua_crash.log", "w")
	if log_file then
		log_file:write("--- HYPRLAND LUA HATASI ---\n" .. tostring(error_message))
		log_file:close()
	end
end
